name: hmu
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^2.0.1
  flutter_bloc: ^5.0.1
  # Value equality
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  data_connection_checker: ^0.3.4
  # Local cache
  shared_preferences: ^0.5.12+4
  # UI Dependecies
  flushbar: ^1.10.4
  flutter_spinkit: "^4.1.2"
  flutter_svg: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - locales/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Eina01
      fonts:
        - asset: assets/fonts/Eina01.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
